export type TPlayer = {
  "id": number, // 758,
  "sport_id": number, // 1,
  "country_id": number, // 462,
  "nationality_id": number, // 462,
  "city_id": number | null, // null,
  "position_id": number, // 25,
  "detailed_position_id": number, // 154,
  "type_id": number, // 25,
  "common_name": string, // "J. Tavernier",
  "firstname": string, // "James",
  "lastname": string, // "Tavernier",
  "name": string, // "James Tavernier",
  "display_name": string, // "James Tavernier",
  "image_path": string, // "https://cdn.sportmonks.com/images/soccer/players/22/758.png",
  "height": number, // 182,
  "weight": number, // 75,
  "date_of_birth": string, // "1991-10-31",
  "gender": string, // "male"
};
